export const univData = [
  {
    name: "Institut Sains & Teknologi Akprind",
  },
  {
    name: "STMIK AMIKOM Yogyakarta",
  },
  {
    name: "Universitas Katolik Indonesia Atma Jaya",
  },
  {
    name: "Universitas Bakrie",
  },
  {
    name: "Binus University",
  },
  {
    name: "Universitas Bung Hatta",
  },
  {
    name: "Universitas Dian Nuswantoro",
  },
  {
    name: "Universitas Gunadarma",
  },
  {
    name: "Universitas Ibn Chaldun Jakarta",
  },
  {
    name: "Universitas Indonusa Esa Unggul",
  },
  {
    name: "Bogor Agricultural University",
  },
  {
    name: "Institut Sains dan Teknologi Al Kamal",
  },
  {
    name: "Institut Teknologi Adhi Tama Surabaya",
  },
  {
    name: "Institut Teknologi Bandung",
  },
  {
    name: "Institut Teknologi Sepuluh Nopember",
  },
  {
    name: "Universitas Janabadra",
  },
  {
    name: "Universitas Jayabaya",
  },
  {
    name: "Universitas Ma Chung",
  },
  {
    name: "Universitas Mahendradatta",
  },
  {
    name: "Universitas Negeri Malang",
  },
  {
    name: "Universitas Kristen Maranatha",
  },
  {
    name: "Universitas Mercu Buana",
  },
  {
    name: "Universitas Dr. R. Moestopo",
  },
  {
    name: "Universitas Narotama",
  },
  {
    name: "Universitas HKBP Nommensen",
  },
  {
    name: "Universitas Pembangunan Panca Budi",
  },
  {
    name: "Universitas Paramadina Mulya",
  },
  {
    name: "Universitas Nasional Pasim",
  },
  {
    name: "STIE Perbanas",
  },
  {
    name: "Perbanas Institute",
  },
  {
    name: "Universitas Kristen Petra",
  },
  {
    name: "Prasetiya Mulya Business School",
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.uns.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Sebelas Maret",
    domains: ["uns.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unsada.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Darma Persada",
    domains: ["unsada.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unsil.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Siliwangi",
    domains: ["unsil.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unsoed.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Jenderal Soedirman",
    domains: ["unsoed.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unsrat.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Sam Ratulangi",
    domains: ["unsrat.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unsri.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Sriwijaya",
    domains: ["unsri.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unswagati-crb.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Swadaya Gunung Djati",
    domains: ["unswagati-crb.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unsyiah.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Syiah Kuala",
    domains: ["unsyiah.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untad.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Tadulako",
    domains: ["untad.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untag.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas 17 Agustus 1945 Surabaya",
    domains: ["untag.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untag-banyuwangi.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas 17 Agustus 1945 Banyuwangi",
    domains: ["untag-banyuwangi.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untagcirebon.info/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas 17 Agustus 1945 Cirebon",
    domains: ["untagcirebon.info"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untag-jkt.org/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas 17 Agustus 1945 Jakarta",
    domains: ["untag-jkt.org"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untag-smd.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas 17 Agustus 1945 Samarinda",
    domains: ["untag-smd.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untagsmg.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas 17 Agustus 1945 Semarang",
    domains: ["untagsmg.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untan.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Tanjungpura",
    domains: ["untan.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untar.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Tarumanagara",
    domains: ["untar.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.untirta.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Sultan Ageng Tirtayasa",
    domains: ["untirta.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unud.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Udayana",
    domains: ["unud.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.unwiku.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Wijaya Kusuma Purwokerto",
    domains: ["unwiku.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.uny.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Negeri Yogyakarta",
    domains: ["uny.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.up45.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Proklamasi 45",
    domains: ["up45.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.uph.edu/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Pelita Harapan",
    domains: ["uph.edu"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.upi.edu/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Pendidikan Indonesia",
    domains: ["upi.edu"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.upnjatim.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: 'Universitas Pembangunan Nasional "Veteran" East Java',
    domains: ["upnjatim.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.upr.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Palangka Raya",
    domains: ["upr.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.upstegal.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Pancasakti Tegal",
    domains: ["upstegal.ac.id"],
  },
  {
    alpha_two_code: "ID",
    web_pages: ["http://www.usd.ac.id/"],
    country: "Indonesia",
    "state-province": null,
    name: "Universitas Sanata Dharma",
    domains: ["usd.ac.id"],
  },
];
